spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  thymeleaf:
    prefix: classpath:/webapp/templates/
    check-template-location: false

  web:
    resources:
      static-locations: classpath:/webapp/
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: ${spring.mail.host}
    port: ${spring.mail.port}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      
image:
  local: true
googlemap:
  client:
    key: ${googlemap.client.key}