spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  thymeleaf:
    prefix: classpath:/webapp/templates/

  web:
    resources:
      static-locations: classpath:/webapp/
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
image:
  local: true