spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  thymeleaf:
    prefix: classpath:/webapp/templates/
    check-template-location: false

  web:
    resources:
      static-locations: classpath:/webapp/
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      
  jpa:
    database: POSTGRESQL
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/website
    username: ${psql.user}
    password: ${psql.password}
      
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: ${spring.mail.host}
    port: ${spring.mail.port}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  messages:
    encoding: UTF-8
      
image:
  local: true
googlemap:
  client:
    key: ${googlemap.client.key}

push7:
  id: ${push7.id}